export const DEPENDENCY_BOOTSTRAP_COMMAND = [
  "set -eu",
  "nested_node_file=$(find . \\( -path '*/.git' -o -path '*/node_modules' \\) -prune -o -type f \\( -name package.json -o -name package-lock.json -o -name npm-shrinkwrap.json -o -name pnpm-lock.yaml -o -name yarn.lock \\) ! -path './package.json' ! -path './package-lock.json' ! -path './npm-shrinkwrap.json' ! -path './pnpm-lock.yaml' ! -path './yarn.lock' -print -quit)",
  'if [ -n "$nested_node_file" ]; then',
  "printf '%s\\n' 'Nested Node package roots are not supported by the verifier' >&2",
  "exit 65",
  "fi",
  "lockfile_count=0",
  "for lockfile in package-lock.json npm-shrinkwrap.json pnpm-lock.yaml yarn.lock; do",
  'if [ -f "$lockfile" ]; then lockfile_count=$((lockfile_count + 1)); fi',
  "done",
  'if [ "$lockfile_count" -gt 1 ]; then',
  "printf '%s\\n' 'Exactly one supported root lockfile is required' >&2",
  "exit 65",
  "fi",
  'if [ "$lockfile_count" -eq 1 ] && [ ! -f package.json ]; then',
  "printf '%s\\n' 'A root package.json is required with the lockfile' >&2",
  "exit 65",
  "fi",
  "if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then",
  'node -e \'const p=JSON.parse(require("node:fs").readFileSync("package.json","utf8"));const m=p.packageManager;if(m!==undefined&&(typeof m!=="string"||!/^npm@[0-9]+\\.[0-9]+\\.[0-9]+(?:[-+][0-9A-Za-z.-]+)?$/.test(m)))process.exit(65)\'',
  "npm ci --ignore-scripts --no-audit --no-fund",
  "elif [ -f pnpm-lock.yaml ]; then",
  'PACKAGE_MANAGER=$(node -e \'const p=JSON.parse(require("node:fs").readFileSync("package.json","utf8"));const m=p.packageManager;if(typeof m!=="string"||!/^pnpm@[0-9]+\\.[0-9]+\\.[0-9]+(?:[-+][0-9A-Za-z.-]+)?$/.test(m))process.exit(65);process.stdout.write(m)\')',
  'corepack "$PACKAGE_MANAGER" install --frozen-lockfile --ignore-scripts',
  "elif [ -f yarn.lock ]; then",
  'PACKAGE_MANAGER=$(node -e \'const p=JSON.parse(require("node:fs").readFileSync("package.json","utf8"));const m=p.packageManager;if(typeof m!=="string"||!/^yarn@[0-9]+\\.[0-9]+\\.[0-9]+(?:[-+][0-9A-Za-z.-]+)?$/.test(m))process.exit(65);process.stdout.write(m)\')',
  'case "$PACKAGE_MANAGER" in',
  'yarn@0.*|yarn@1.*) corepack "$PACKAGE_MANAGER" install --frozen-lockfile --ignore-scripts --non-interactive ;;',
  '*) YARN_ENABLE_SCRIPTS=false corepack "$PACKAGE_MANAGER" install --immutable --mode=skip-build ;;',
  "esac",
  "elif [ -f package.json ]; then",
  "printf '%s\\n' 'A supported frozen lockfile is required for verification' >&2",
  "exit 65",
  "fi",
].join("\n");
